#include "../../php_opencv.h"

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

void highgui_init(int module_number)
{
    /**
     * ! Flags for CV::imshow
     */
//    REGISTER_LONG_CONSTANT("WINDOW_NORMAL", WINDOW_NORMAL, CONST_CS | CONST_PERSISTENT);
//    REGISTER_LONG_CONSTANT("WINDOW_AUTOSIZE", WINDOW_AUTOSIZE, CONST_CS | CONST_PERSISTENT);
//    REGISTER_LONG_CONSTANT("WINDOW_OPENGL", WINDOW_OPENGL, CONST_CS | CONST_PERSISTENT);
//    REGISTER_LONG_CONSTANT("WINDOW_FULLSCREEN", WINDOW_FULLSCREEN, CONST_CS | CONST_PERSISTENT);
//    REGISTER_LONG_CONSTANT("WINDOW_FREERATIO", WINDOW_FREERATIO, CONST_CS | CONST_PERSISTENT);
//    REGISTER_LONG_CONSTANT("WINDOW_GUI_EXPANDED", WINDOW_GUI_EXPANDED, CONST_CS | CONST_PERSISTENT);
//    REGISTER_LONG_CONSTANT("WINDOW_GUI_NORMAL", WINDOW_GUI_NORMAL, CONST_CS | CONST_PERSISTENT);
}