#include "../../../php_opencv.h"
#include "opencv_base.h"

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif


void opencv_border_types_init(int module_number){
    //! Various border types, image boundaries are denoted with `|`
    //! @see borderInterpolate, copyMakeBorde
    REGISTER_NS_LONG_CONSTANT(OPENCV_NS, "BORDER_CONSTANT", BORDER_CONSTANT, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT(OPENCV_NS, "BORDER_REPLICATE", BORDER_REPLICATE, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT(OPENCV_NS, "BORDER_REFLECT", BORDER_REFLECT, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT(OPENCV_NS, "BORDER_WRAP", BORDER_WRAP, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT(OPENCV_NS, "BORDER_REFLECT_101", BORDER_REFLECT_101, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT(OPENCV_NS, "BORDER_TRANSPARENT", BORDER_TRANSPARENT, CONST_CS | CONST_PERSISTENT);

    REGISTER_NS_LONG_CONSTANT(OPENCV_NS, "BORDER_REFLECT101", BORDER_REFLECT101, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT(OPENCV_NS, "BORDER_DEFAULT", BORDER_DEFAULT, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT(OPENCV_NS, "BORDER_ISOLATED", BORDER_ISOLATED, CONST_CS | CONST_PERSISTENT);
}
